feat: hash validation on Verify page when key is missing from …
uncefact/tests-untp pull request #153
Opened 2024-11-04 08:08 UTC by ldhyen99

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

2024-11-04 08:44 UTC, namhoang1604 requested changes

2024-11-04 08:44 UTC, namhoang1604 commented on packages/mock-app/src/pages/Verify.tsx
> +        return verifyHash(encryptedCredential);
@ldhyen99 the code looks like we are not handling decrypting the enveloped credential. Should we add the decryption for it?

2024-11-04 09:43 UTC, namhoang1604 submitted a review, later dismissed

2024-11-04 09:44 UTC, huynguyen-hl commented on documentation/docs/mock-apps/verify-app.md
> +## Hash validation (if it exist in URL)
Should we update this sentence to `Hash validation (if it exists in the URL)` to make it more grammatically correct?

2024-11-05 02:30 UTC, namhoang1604 approved these changes

2024-11-05 02:31 UTC, huynguyen-hl approved these changes

2024-11-05 02:40 UTC, merged