chore: add common UI components
uncefact/tests-untp pull request #4
Opened 2024-01-25 06:38 UTC by huynguyen-hl

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [x] 📜 README.md
- [x] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

2024-01-25 07:32 UTC, namhoang1604 requested changes
Can you please correct the commit message?

2024-01-25 07:32 UTC, namhoang1604 commented on packages/components/package.json
> +    "test": "jest --ci --env=jest-environment-jsdom --collect-coverage"
Please one more script for coverage

2024-01-25 07:32 UTC, namhoang1604 commented on packages/components/src/common-components/README.md
I think we don't need readme for common components

2024-01-25 07:32 UTC, namhoang1604 commented on packages/components/src/common-components/ToastMessage/ToastMessage.tsx
How to use ToastMessage as a service? We want the ToastMessage to be set up at App and use its service to trigger messages. That should have the guideline.

2024-01-25 09:49 UTC, huynguyen-hl commented on packages/components/src/common-components/ToastMessage/ToastMessage.tsx
I have just updated the ToastMessage component to be more convenient when setting up and triggering messages.

2024-01-25 12:11 UTC, huynguyen-hl commented
> Can you please correct the commit message?

Yes, I just updated that commit

2024-01-26 07:51 UTC, namhoang1604 approved these changes
LGTM

2024-01-26 07:57 UTC, ldhyen99 approved these changes

2024-01-26 09:02 UTC, namhoang1604 approved these changes

2024-01-26 10:22 UTC, ldhyen99 approved these changes

2024-01-26 10:23 UTC, merged