feat: add base event service
uncefact/tests-untp pull request #7
Opened 2024-01-29 06:49 UTC by ldhyen99

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [x] 📜 README.md
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

2024-01-29 07:00 UTC, namhoang1604 requested changes

2024-01-29 07:00 UTC, namhoang1604 commented on packages/services/src/vckit.service.ts
> +    const response = await publicAPI.post(`${process.env.REACT_APP_VCKIT_API_URL ?? ''}/credentials/issue`, body);
process.env.REACT_APP_VCKIT_API_URL, the variable will be imported from the configuration, so it should be a parameter of function

2024-01-29 07:01 UTC, huynguyen-hl commented on packages/services/src/baseEvent.service.ts
> +      const credentialValue = result;
I think we can use 'credentialValue' name instead of 'result' name

2024-01-29 07:37 UTC, namhoang1604 commented on packages/services/src/types/types.ts
> +}
this interface look the same IVcKitIssueVC https://github.com/uncefact/tests-untp/pull/7/files#diff-c027e5b988fa430c7172d5d0e5853b55eef18c83276399b385400f3748329138R5-R7

2024-01-29 07:39 UTC, huynguyen-hl approved these changes

2024-01-29 07:51 UTC, namhoang1604 approved these changes

2024-01-29 09:26 UTC, huynguyen-hl submitted a review, later dismissed

2024-01-31 02:49 UTC, huynguyen-hl submitted a review, later dismissed

2024-02-19 09:14 UTC, namhoang1604 approved these changes

2024-02-19 10:38 UTC, huynguyen-hl approved these changes

2024-02-20 02:22 UTC, merged